### ISSUE TITLE
RxJS refactoring TODO

### ISSUE THREAD

**Issue by destegabry** [arduino/arduino-create-agent-js-client#6]
- [x]  add polling to check agent connection
- [x]  turn off web socket polling when agent is down
- [x]  add RxJS Subject to know which devices are connected
- [x] implement open and close serial monitor
- [x] implement write and read on serial monitor
